### PR TITLE
Bumped ppom, http and asto

### PR DESCRIPTION
**Pull request by olenagerasimova**
Updated dependencies and fixed compilation issues

### CODE REVIEW

**Comment by olenagerasimova** [comment]
@olegmoz please review/merge/release

**Review by olegmoz — APPROVED** [review]
@olenagerasimova thanks

**Comment by olegmoz** [comment]
@yegor256 could you please touch `.rultor`, so we can create new release?

**Comment by 0crat** [comment]
Job `gh:artipie/helm-adapter#71` is not assigned, can't get performer

**Comment by yegor256** [comment]
@olegmoz done

**Comment by olegmoz** [comment]
@yegor256 thanks

**Comment by olegmoz** [comment]
@rultor release, tag=`0.1.4`

**Pull request merged**
