### PR TITLE
Reference index.yaml generation in a temp dir

### PR DESCRIPTION
**Pull request by Sammers21**
Related to #53

What is done:
* Reference `index.yaml` generation performed in a temporary directory
* Tests logging has been enabled, so the generated files are logged

### CODE REVIEW

**Comment by Sammers21** [comment]
@g4s8, review the Pull Request please

**Comment by 0crat** [comment]
This pull request [#54](https://github.com/artipie/helm-adapter/issues/54) is assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/b3704c77-d0a5-4b52-b487-0c318dfe5f97); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job was finished in 20 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @vatavuk[/z](https://www.0crat.com/u/vatavuk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by g4s8** [comment]
@0crat quality bad

**Pull request merged**
