### PR TITLE
Auth support

### PR DESCRIPTION
**Pull request by Sammers21**
Related to #11

### CODE REVIEW

**Comment by Sammers21** [comment]
@olegmoz, can you review?

**Comment by 0crat** [comment]
This pull request [#55](https://github.com/artipie/helm-adapter/issues/55) is assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/f8226227-54e7-4b86-876f-db4a64124bbc); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by Sammers21** [comment]
@olegmoz, I want to do it in a subsequent pull request.

**Comment by Sammers21** [comment]
@olegmoz, we already have a test an integration test uses the slice with anonymous credentials, so the slice would not be broken in a result.

**Comment by olegmoz** [comment]
@Sammers21 that's nice, but I am talking about having the new auth feature covered with tests. What's you reasoning for not doing that in this PR?

**Comment by Sammers21** [comment]
@olegmoz, it is not a trivial task which requires significant efforts, that is why it should be done in a separated pull request.

**Comment by olegmoz** [comment]
@Sammers21 you may write a unit test, not an integration test, that would be quite easy

**Comment by Sammers21** [comment]
@olegmoz, a unit test for an http auth layer?

**Comment by olegmoz** [comment]
@Sammers21 test for `HelmSlice` class that now may require certain permissions

**Comment by Sammers21** [comment]
@olegmoz, i have created a puzzle for auth test

**Comment by Sammers21** [comment]
@g4s8, can we merge?

**Comment by g4s8** [comment]
@Sammers21 I agree with @olegmoz , please cover such changes with tests next time.

**Comment by 0crat** [comment]
Job was finished in 23 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @vatavuk[/z](https://www.0crat.com/u/vatavuk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by Sammers21** [comment]
@g4s8, can you release a new version?

**Comment by g4s8** [comment]
@Sammers21 sure, see: https://github.com/artipie/helm-adapter/issues/11#issuecomment-655339377

**Comment by Vatavuk** [comment]
@sereshqua ping

**Pull request merged**
