### PR TITLE
For #14: PushSliceChart test

### PR DESCRIPTION
**Pull request by paulodamaso**
For #14:
- created `SliceChartTest` 
- removed puzzle

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#48](https://github.com/artipie/helm-adapter/issues/48) is assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/1b7c68da-aa1e-4208-82ae-e17bb3d3494d); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by 0crat** [comment]
This pull request [#48](https://github.com/artipie/helm-adapter/issues/48) is assigned to @sammers21[/z](https://www.0crat.com/u/sammers21), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/58d3c600-932d-491e-b5ad-1977b686cc5f); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; @sammers21[/z](https://www.0crat.com/u/sammers21) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; we should be aware that @sammers21[/z](https://www.0crat.com/u/sammers21) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by 0crat** [comment]
@sammers21[/z](https://www.0crat.com/u/sammers21) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by Sammers21** [comment]
@paulodamaso, close the PR, please.

**Comment by Sammers21** [comment]
@g4s8, close the Pull Request

**Comment by Sammers21** [comment]
@g4s8, ping

**Comment by paulodamaso** [comment]
@g4s8 please take a look at this.

**Comment by paulodamaso** [comment]
@g4s8 ping

**Comment by Sammers21** [comment]
@paulodamaso, the puzzle has already been solved and, considering the title(Create an integration test), it is clear that your PR is not related to this puzzle in any way. Stop ignoring me and CLOSE THE PULL REQUEST!!!

**Comment by paulodamaso** [comment]
@g4s8 I need your take on this one

**Comment by 0crat** [comment]
@sammers21[/z](https://www.0crat.com/u/sammers21) resigned from [#48](https://github.com/artipie/helm-adapter/issues/48), since the job is not in scope anymore

**Comment by 0crat** [comment]
Pull request [#48](https://github.com/artipie/helm-adapter/issues/48) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Pull request closed without merging**
