### PR TITLE
Implement Index#empty

### PR DESCRIPTION
**Pull request by Sammers21**
_Closes #31

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#33](https://github.com/artipie/helm-adapter/issues/33) is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/aa0f5e88-7daa-48e8-9c68-89212e758c50); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@Sammers21 The code is untested, please add the test to the PR

**Comment by Sammers21** [comment]
> @Sammers21 PLease add the tests

@paulodamaso, just created a puzzle

**Comment by g4s8** [comment]
@Sammers21 this PR is too small, please create a unit test

**Comment by Sammers21** [comment]
@g4s8, the method I implement in this PR is private, I could not test it

**Comment by Sammers21** [comment]
@g4s8, ping

**Comment by g4s8** [comment]
@Sammers21 but this private method is used by other methods, so you can write a test for this public method, isn't it?

**Comment by Sammers21** [comment]
@g4s8, this public method would not work properly if I implement only this empty method. I need `#update` to be implemented as well.

**Comment by Sammers21** [comment]
@g4s8, ping

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@paulodamaso please make are you will find at least 3 issues during next CR, thanks

**Comment by paulodamaso** [comment]
@sereshqua I will try to find at least 3 issues in my next review, thank you

**Comment by sereshqua** [comment]
@0crat quality acceptable

**Pull request merged**
